version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
    labels:
      - 'dependencies'
  # Maintain NPM Packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'eslint'
          - 'typescript'
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: 'eslint'
      - dependency-name: 'typescript'
