name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

env:
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ vars.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      # TODO: When pnpm/setup finally fixes @v2 to point to latest version, change to @v2
      - name: Setup pnpm and runtime
        uses: pnpm/setup@v2.1.0
        with:
          cache: true
          require-lockfile: true

      - name: Pre Build
        run: pnpm run pre

      - name: Build
        run: pnpm run build

      - name: Upload
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
